[package]
name = "uf2_hash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uf2_hash_cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.89"
bytes = "1.7.2"
clap = { version = "4.5.20", features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }
